version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: 
     - .env
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - inception_net

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - inception_net

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - 'wordpress:/var/www/html'
    networks:
      - inception_net

volumes:
  mariadb:
  wordpress:

networks:
  inception_net:
    driver: bridge
